GENCODE_RELEASE = '39'
REFERENCE = 'GRCh38.v' + GENCODE_RELEASE
REFERENCE_FASTA_URL = f'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_{GENCODE_RELEASE}/GRCh38.p13.genome.fa.gz'

rule all:
    input:
        expand(f'{REFERENCE}.genome.{{sufx}}',
               sufx=['fa.gz', 'mm2.idx', 'fa.gz.amb', 'fa.gz.ann',
                     'fa.gz.bwt', 'fa.gz.pac', 'fa.gz.sa'])

rule download_genome_fasta:
    output: f'{REFERENCE}.genome.fa.gz'
    shell: 'curl {REFERENCE_FASTA_URL} > {output}'

rule build_minimap2_genome_index:
    input: f'{REFERENCE}.genome.fa.gz'
    output: f'{REFERENCE}.genome.mm2.idx'
    shell: 'zcat {input} | minimap2 -k 13 -d {output} /dev/stdin'

rule build_bwa_genome_index:
    input: f'{REFERENCE}.genome.fa.gz'
    output:
        expand(f'{REFERENCE}.genome.fa.gz.{{sufx}}', sufx=['amb', 'ann', 'bwt', 'pac', 'sa'])
    shell: 'bwa index {input}'
